"""Utility primitives for the (step × layer) low-rank spectral analysis."""

from .spectral import (
    token_cloud_singular_values,
    effective_rank,
    spectral_energy,
    top_concentration,
    effective_rank_truncated,
    step_layer_spectral_summary,
    step_layer_cim_summary,
    cim_tle_intrinsic_dim,
    cim_information_volume,
    lowrank_decompose,
    chain_lowrankness,
    step_residual_norms,
    layer_residual_norms,
    layer_profile_corr_with_prefix,
    compute_unembedding_svd,
    select_reasoning_subspace,
    project_to_reasoning,
)
from .step_boundaries import (
    find_step_token_ranges,
    split_response_into_steps,
)
from .geometry import (
    cloud_geometry,
    centroid_step_drift,
    centroid_curvature,
    principal_angles,
    principal_angle_drift,
    grassmann_distance,
    bures_distance,
    gaussian_w2,
    gaussian_w2_step_drift,
    align_basis,
)

__all__ = [
    "token_cloud_singular_values",
    "effective_rank",
    "spectral_energy",
    "top_concentration",
    "effective_rank_truncated",
    "step_layer_spectral_summary",
    "step_layer_cim_summary",
    "cim_tle_intrinsic_dim",
    "cim_information_volume",
    "lowrank_decompose",
    "chain_lowrankness",
    "step_residual_norms",
    "layer_residual_norms",
    "layer_profile_corr_with_prefix",
    "compute_unembedding_svd",
    "select_reasoning_subspace",
    "project_to_reasoning",
    "find_step_token_ranges",
    "split_response_into_steps",
    "cloud_geometry",
    "centroid_step_drift",
    "centroid_curvature",
    "principal_angles",
    "principal_angle_drift",
    "grassmann_distance",
    "bures_distance",
    "gaussian_w2",
    "gaussian_w2_step_drift",
    "align_basis",
]